<?php
    /**
     * Implements hook_menu().
     */
    function fightpoverty_menu() {

        $items['fightpoverty/'] = array(
            'title' => 'fightpoverty title',
            'page callback' => 'chooseproj_callback',
            'access arguments' => array('access content'),
            /*'page arguments' => array(1),*/
            'access callback' => 'user_access',
            'type' => MENU_CALLBACK,
        );

        $items['fightpovertychooseproj/%'] = array(
            'title' => 'fightpoverty title',
            'page callback' => 'chooseproj_callback',
            'access arguments' => array('access content'),
            'page arguments' => array(1),
            'access callback' => 'user_access',
            'type' => MENU_CALLBACK,
        );

    return $items;
    }
    function test_ajax_link_response($type = 'ajax') {
        if ($type == 'ajax') {
            $output = t("This is some content delivered via AJAX");
            $commands = array();
            // See ajax_example_advanced.inc for more details on the available commands
            // and how to use them.
            $commands[] = ajax_command_append('#myDiv', $output);
            $page = array('#type' => 'ajax', '#commands' => $commands);
            ajax_deliver($page);
        }
        else {
            $output = t("This is some content delivered via a page load.");
            return $output;
        }
    }
    function chooseproj_callback($type, $proj_id){
        global $user;


        $account = user_load( $user->uid ); // Loading account
        $edit = array(
            'field_choosed_project' => array(
                'und' => array(
                    0 => array(
                        'value' => $proj_id,
                    ),
                ),
            ),
        );

        if( user_save($account, $edit) ){

            $output = t("You have chosen this project");
            $commands = array();
            // See ajax_example_advanced.inc for more details on the available commands
            // and how to use them.
            $commands[] = ajax_command_replace( '#div' . $proj_id, $output );
            $page = array('#type' => 'ajax', '#commands' => $commands);
            ajax_deliver($page);

        }


        /*
        $reset_pos_sorting_field = variable_get('reset_pos_sorting_field');
        $reset_pos_days_to_refresh = variable_get('reset_pos_days_to_refresh');
        
        db_update('node')
            ->fields(array($reset_pos_sorting_field => (int) time()))
            ->condition('nid', (int)$_GET['nid'])
            ->condition('uid', (int)$user->uid)
            ->condition($reset_pos_sorting_field, (int)strtotime("-" . $reset_pos_days_to_refresh .
                    " days"),'<=')//changed field if sorting changed
            ->execute();
        
        drupal_exit();*/
    }

    function fightpoverty_form_alter(&$form, &$form_state,$form_id) {
        switch ($form_id) {
            case 'user_register_form':
                $form['#submit'][] = 'fightpoverty_user_register_submit';
                break;
        }
    }

    function fightpoverty_user_register_submit($form, &$form_state) {
        $form_state['redirect'] = url('node/43');//redirects to choose project page
    }
    function choose_proj_fp($project_id) {
        return drupal_get_form('ajax_chooseproj_print_form', $project_id);
    }

    function ajax_chooseproj_print_form($form, &$form_state, $project_id ) {
        $form = array();

        $form['submit_link'] = array(
            '#type' => 'link',
            '#title' => t('Choose project'),
            '#href' => 'fightpovertychooseproj/nojs/' . $project_id,
            '#id' => 'ajax_link' . $project_id,
            '#attributes' => array(
                'class' => array(
                    'use-ajax',
                ),
            ),
            '#ajax' => array(
                'wrapper' => 'ajax_link' . $project_id,
                'method' => 'html',
                'effect' => 'fade'
            ),
        );

        return $form;
    }

function fightpoverty_user_view($account, $view_mode, $langcode) {

    $account->content['field_choosed_project'] = array (  '#weight' => -1000,  '#type' => 'user_profile_category', '#title' => t('Chosen project'),
        '#markup' => '', '#attributes' => array ( 'class' => array ( 0 => 'user-chosen-projects', 1 => 'clearfix', ), ),
        '#access' => true, 'view' => array ( '#type' => 'user_profile_item', '#title' => '', '#markup' => ' ',
            '#attributes' => array ( 'class' => array ( 0 => 'recent-orders', ), ), ), );

    if( !empty($account->field_choosed_project) ){

        $field_choosed_project = field_get_items('user', $account, 'field_choosed_project');
        $chosen_project = field_view_value('user', $account, 'field_choosed_project', $field_choosed_project[0]);

        $project = node_load( $chosen_project['#markup'] );

        $account->content['field_choosed_project']['view']['#markup'] = t('You have chosen:') .' '. l( $project->title .' '. t('project'), 'node/'.$project->nid);

    }else{

        $account->content['field_choosed_project']['view']['#markup'] = l(t('Please choose project to participate'), 'node/43');

    }


}

?>